# Generated by Django 2.2.6 on 2019-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191215_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('tech', 'Tech'), ('education', 'Education'), ('product', 'Product')], max_length=50),
        ),
    ]
